-- This is an example of a file generated by the server before every game.
-- We need to have an extra army `SUPPORT_X` for the reinforcement logic.
-- Before the game starts, a _scenario.lua file is generated to be hooked to the desired map.
-- It needs to be placed in the correct folder structure, with correct folder and map name.
--     - The map's folder and files name are the same by the naming conventions.
--     - Example: /mods/galacticWar/hook/maps/SCMP_001/SCMP_001_scenario.lua

-- The name is hooked just for the debugging purposes to indicare the map got hooked correctly.
ScenarioInfo.name = ScenarioInfo.name .. " GW"
-- Support armies are added for both teams for the reinforcements logic.
ScenarioInfo.Configurations['standard'].customprops['ExtraArmies'] = STRING( 'ARMY_17 NEUTRAL_CIVILIAN SUPPORT_1 SUPPORT_2' )
